[package]
name = "guess_game"
version = "0.1.0"
authors = ["Prashant Singh <fet.prashantsingh@gmail.com> "]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"